name = "mob-games"
author = "leafd, thomas"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d2b85a0c9023bfcebba6e44fd425f316c306a04c2404f79d446218c2161b8e2"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
