---
name: Release
"on":
  workflow_dispatch: null
  push:
    branches:
      - main
    paths:
      - serverpack/**
concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ toJSON(steps.rp.outputs) }}
    steps:
      - name: Generate App Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Release Please
        id: rp
        uses: GoogleCloudPlatform/release-please-action@v4.1.3
        with:
          token: ${{ steps.generate-token.outputs.token }}

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: ${{ fromJSON(needs.release-please.outputs.manifest).releases_created == 'true' }}
    needs: [release-please]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


